"""
ORM model definitions for SentinelX.

Tables:
  - alerts:   security events generated by monitors and response actions
  - settings: key/value configuration persisted across restarts
"""

import datetime

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Alert(Base):
    """A single security alert recorded by the EDR engine."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    type = Column(String)  # PROCESS, FILE, NETWORK, USB, AI
    severity = Column(String)  # INFO, WARNING, CRITICAL
    source = Column(String)  # e.g., "miner.exe", "invoice.pdf.exe"
    message = Column(String)
    threat_score = Column(Float, nullable=True)
    explanation = Column(String, nullable=True)
    status = Column(String, default="ACTIVE")  # ACTIVE, KILLED, QUARANTINED, DISMISSED


class Setting(Base):
    """Key/value application setting stored in SQLite."""

    __tablename__ = "settings"

    key = Column(String, primary_key=True, index=True)
    value = Column(String)

class User(Base):
    """Application users for authentication and role-based access."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)

    username = Column(String, unique=True, nullable=False, index=True)

    password = Column(String, nullable=False)

    role = Column(String, nullable=False, default="VIEWER")
    # ADMIN | ANALYST | VIEWER

    is_active = Column(Boolean, default=True)

    created_at = Column(DateTime, default=datetime.datetime.utcnow)
